### PR TITLE
Show pointer when touching without moving

### PR DESCRIPTION
**Pull request by sybrands-place**

### CODE REVIEW

**Comment by sybrands-place** [comment]
@Mardaneus86 any interest in this pull request?

**Comment by Mardaneus86** [comment]
Looks like I missed this PR initially, sorry for that.

What is not working without this PR?

**Comment by sybrands-place** [comment]
onPointerDown it will show a touch indicator when touching the screen. without it it only shows it when releasing it (touch down + touch up = click).

**Comment by Mardaneus86** [comment]
I see, thanks for the clarification.

~~Can you remove the changes to the `CHANGELOG.md` and `pubspec.yaml` files? Versioning isn't for PR's.~~ Nevermind, I haven't created a proper `develop` branch yet, so you can leave it in. Creating proper instructions for PR's is on my todo list now 👍

**Comment by Mardaneus86** [comment]
This has been released in [v1.0.3](https://pub.dev/packages/touch_indicator/versions/1.0.3). Thanks for the contribution!

**Pull request merged**
